services:
  db:
    image: mysql:8.0
    container_name: mysql_investimentos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: investimentos
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend_investimentos
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: mysql://dev:devpass@db:3306/investimentos
      SHADOW_DATABASE_URL: mysql://dev:devpass@db:3306/prisma_migrate_shadow_db
      SECRET_KEY: "your_secret_key_here"
      DEBUG: "true"
      ALLOWED_HOSTS: "localhost"
    networks:
      - app-network
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npx ts-node src/seed.ts && npm run dev"

  
volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
